# Generated by Django 4.2.4 on 2023-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grocery_remove_item_brand_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
