# Generated by Django 4.2.4 on 2023-08-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('core', '0003_grocery_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
