# Generated by Django 4.2.4 on 2023-08-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('core', '0004_grocery_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='get',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
