# Generated by Django 4.2.4 on 2023-08-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_max_stock_qty_alter_item_min_stock_qty_and_more'),
        ('core', '0005_alter_grocery_comments_alter_grocery_get_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='item',
        ),
        migrations.AddField(
            model_name='grocery',
            name='item',
            field=models.ManyToManyField(to='items.item'),
        ),
    ]
