# Generated by Django 4.2.4 on 2023-08-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('core', '0006_remove_grocery_item_grocery_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='item',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.store'),
        ),
    ]
