# Generated by Django 4.2.4 on 2023-08-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_max_stock_qty_alter_item_min_stock_qty_and_more'),
        ('core', '0007_remove_grocery_comments_remove_grocery_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.item'),
        ),
    ]
