# Generated by Django 4.2.4 on 2023-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grocery_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
