# Generated by Django 4.2.4 on 2023-08-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='min_stock_qty',
            field=models.IntegerField(),
        ),
    ]
