# Generated by Django 4.2.4 on 2023-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='max_stock_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='min_stock_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_qty',
            field=models.IntegerField(default=0),
        ),
    ]
